version: "3"
services:
  grafana:
    image: grafana/grafana
    container_name: grafana
    restart: always
    networks:
    - grafana-net
    volumes:
    - grafana-volume

  graphite:
    image: graphiteapp/graphite-statsd
    container_name: graphite
    restart: always
    networks:
    - grafana-net

  nginx:
    image: nginx:latest
    container_name: production_nginx
    volumes:
    - ./nginx.conf:/etc/nginx/nginx.conf
    - /etc/letsencrypt/:/etc/letsencrypt/
    networks:
    - grafana-net
    ports:
    - 80:80
    - 443:443
    depends_on:
    - grafana

  app:
    image: ruby:2.5
    container_name: app
    env_file:
    - creds.env
    networks:
    - grafana-net
    volumes:
    - ./app:/var/app
    working_dir: /var/app
    command: "./entrypoint.sh"
    depends_on:
      - graphite

  java_app:
    build:
      context: java_app
    container_name: javaapp
    env_file:
      - creds.env
    networks:
      - grafana-net
    volumes:
      - ./java_app:/var/app
    command: mvn clean package exec:java -D exec.mainClass=net.corrupt.stats.Application
    depends_on:
      - graphite

networks:
  grafana-net:

volumes:
  grafana-volume:
    external: true
