{
 "title": "Tesla",
 "time": { "from": "now-12h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Odometer",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "stats.gauges.tesla.response.vehicle_state.odometer"
    }
   ]
  },
  {
   "title": "Battery",
   "type": "graph",
   "gridPos": { "h": 6, "w": 10, "x": 3, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.tesla.response.charge_state.battery_level"
    },
    {
     "target": "stats.gauges.tesla.response.charge_state.battery_range"
    }
   ]
  },
  {
   "title": "Temp",
   "type": "graph",
   "gridPos": { "h": 6, "w": 11, "x": 13, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.tesla.response.climate_state.inside_temp"
    },
    {
     "target": "stats.gauges.tesla.response.climate_state.outside_temp"
    }
   ]
  },
  {
   "title": "Charging Volts",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 2 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "maxSeries(stats.gauges.tesla.response.charge_state.charger_voltage)"
    }
   ]
  },
  {
   "title": "Charger Amps",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 4 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "target": "maxSeries(stats.gauges.tesla.response.charge_state.charger_power)"
    }
   ]
  },
  {
   "title": "Driving",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "target": "stats.gauges.tesla.response.drive_state.power"
    },
    {
     "target": "stats.gauges.tesla.response.drive_state.speed"
    }
   ]
  },
  {
   "title": "Response Code",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "target": "stats.gauges.tesla.statusCode" }
   ]
  }
 ]
}